spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://13.125.18.81:3306/ict?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      #jdbc-url: jdbc:mysql://43.200.138.19:3306/ict?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      #jdbc-url: jdbc:mysql://3.37.139.180:3306/ict?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ictuser
      password: gksghk12!
      pool-name: cp_my
      maximum-pool-size: 20
      max-lifetime: 26000
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 9002
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      tracking-modes: cookie
  reactive:
    session:
      timeout: 120m
  shutdown: graceful

springfox:
  documentation:
    swagger:
      use-model-v3: false

logging:
  level:
    root: info