spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${JDBC_DATABASE_URL}
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}
      pool-name: cp_my
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      validation-timeout: 3000
      auto-commit: true
      keepalive-time: 150000
      data-source-properties:
        socketTimeout: 20
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 9002
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      tracking-modes: cookie
  reactive:
    session:
      timeout: 120m
  shutdown: graceful

springfox:
  documentation:
    swagger:
      use-model-v3: false

logging:
  level:
    root: info